POST http://localhost:3000/user/register
Content-Type: application/json

{
    "name": "Claire Evans",
    "email": "cevans@gmail.com",
    "password": "ya2"

}
###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "cevans@gmail.com",
    "password": "ya2"
}
###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "santiago@gmail.com",
    "password": "ya"
}
###

GET http://localhost:3000/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYzEzYmQyYzU3MzRlZTk5ZWNiYzIxZCIsImlhdCI6MTY1NjgzNTA0MCwiZXhwIjoxNjU5NDI3MDQwfQ.CN5etCHfYc3zzJqMGtObnq0HsEOFBy4BkcrXo24puLg



###
POST http://localhost:3000/posts/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYzEzYmQyYzU3MzRlZTk5ZWNiYzIxZCIsImlhdCI6MTY1NjgzNTA0MCwiZXhwIjoxNjU5NDI3MDQwfQ.CN5etCHfYc3zzJqMGtObnq0HsEOFBy4BkcrXo24puLg
Content-Type: application/json

{
    "title": "The mountains",
    "description": "Green mountain on the top",
    "likes" : 0,
    "location": "Colombia"
}

###
GET http://localhost:3000/posts/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYzEzYmQyYzU3MzRlZTk5ZWNiYzIxZCIsImlhdCI6MTY1NjgzNTA0MCwiZXhwIjoxNjU5NDI3MDQwfQ.CN5etCHfYc3zzJqMGtObnq0HsEOFBy4BkcrXo24puLg



